# Generated by Django 4.2.4 on 2024-04-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MuscleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "force",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("static", "Static"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "mechanic",
                    models.CharField(
                        choices=[("compound", "Compound"), ("isolation", "Isolation")],
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("body only", "Body Only"),
                            ("machine", "Machine"),
                            ("kettlebells", "Kettlebells"),
                            ("dumbbell", "Dumbbell"),
                            ("cable", "Cable"),
                            ("barbell", "Barbell"),
                            ("bands", "Bands"),
                            ("medicine ball", "Medicine Ball"),
                            ("exercise ball", "Exercise Ball"),
                            ("e-z curl bar", "E-Z Curl Bar"),
                            ("foam roll", "Foam Roll"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "strength"),
                            ("stretching", "stretching"),
                            ("plyometrics", "plyometrics"),
                            ("strongman", "strongman"),
                            ("powerlifting", "powerlifting"),
                            ("cardio", "cardio"),
                            ("olympic weightlifting", "olympic weightlifting"),
                            ("crossfit", "crossfit"),
                            ("weighted bodyweight", "weighted bodyweight"),
                            ("assisted bodyweight", "assisted bodyweight"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "primaryMuscles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="primary_muscles",
                        to="exercise.musclegroup",
                    ),
                ),
                (
                    "secondaryMuscles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_muscles",
                        to="exercise.musclegroup",
                    ),
                ),
            ],
        ),
    ]
