# Generated by Django 4.2.4 on 2024-04-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("strength", "Strength"),
                    ("stretching", "Stretching"),
                    ("plyometrics", "Plyometrics"),
                    ("strongman", "Strongman"),
                    ("powerlifting", "Powerlifting"),
                    ("cardio", "Cardio"),
                    ("olympic weightlifting", "Olympic Weightlifting"),
                    ("crossfit", "Crossfit"),
                    ("weighted bodyweight", "Weighted Bodyweight"),
                    ("assisted bodyweight", "Assisted Bodyweight"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="mechanic",
            field=models.CharField(
                choices=[("compound", "Compound"), ("isolation", "Isolation")],
                max_length=100,
                null=True,
            ),
        ),
    ]
