# Generated by Django 4.2.4 on 2024-04-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercise", "0003_alter_exercise_equipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="force",
            field=models.CharField(
                choices=[("push", "Push"), ("pull", "Pull"), ("static", "Static")],
                max_length=100,
                null=True,
            ),
        ),
    ]
