# Generated by Django 4.2.4 on 2024-03-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Default Name", max_length=100)),
                (
                    "email",
                    models.EmailField(
                        default="example@example.com", max_length=254, unique=True
                    ),
                ),
                ("phone", models.CharField(default="000-000-0000", max_length=15)),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("height", models.FloatField(max_length=100)),
                ("width", models.FloatField(max_length=100)),
                ("city", models.CharField(max_length=50)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default-avatar.png",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
            ],
        ),
    ]
