# Generated by Django 4.2.4 on 2024-03-23 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="width",
            new_name="weight",
        ),
    ]
